// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name dashboardApp.controller:AboutCtrl
    * @description
    * # AboutCtrl
    * Controller of the dashboardApp
   */
  angular.module('dashboardApp').controller('searchCtrl', [
    '$scope', '$filter', function(scope, filter) {
      scope.rowCollection = [
        {
          id: 1,
          srcIP: '10.24.1.1',
          dstIP: '10.24.1.3',
          title: 'hoge',
          url: 'http://west.sd.keio.ac.jp',
          browsingTime: 10
        }, {
          id: 2,
          srcIP: '10.24.1.1',
          dstIP: '10.24.1.3',
          title: 'hoge',
          url: 'http://west.sd.keio.ac.jp',
          browsingTime: 10
        }, {
          id: 3,
          srcIP: '10.24.1.1',
          dstIP: '10.24.1.3',
          title: 'hoge',
          url: 'http://west.sd.keio.ac.jp',
          browsingTime: 10
        }, {
          id: 4,
          srcIP: '10.24.1.1',
          dstIP: '10.24.1.3',
          title: 'hoge',
          url: 'http://west.sd.keio.ac.jp',
          browsingTime: 10
        }
      ];

      scope.getters = {
        id: function(value) {
          return value.id.length;
        }
      scope.clicked = function(row) {
        alert(row.getProperty("id"));
      }
      scope.predicates = ['id', 'srcIP', 'dstIP', 'title', 'url', 'browsingTime'];
      scope.selectedPredicate = scope.predicates[0];
      scope.url = 'http://west.sd.keio.ac.jp/';
      scope.title = 'Westlab HomePage';
      return scope.total_count = 111111;
    }
  ]);

}).call(this);

//# sourceMappingURL=search.js.map
