// Generated by CoffeeScript 1.9.1
(function() {
  'use strict';
  var dashboardApp;

  dashboardApp = angular.module('dashboardApp');

  dashboardApp.directive('browsingGraph', function() {
    var link;
    link = function(scope, element, attr) {
      var i, j, links, node, nodes, ref, svg, y_axis;
      svg = d3.select(element[0]).append('svg').attr("width", 800).attr("height", 400);
      y_axis = (function() {
        var y;
        y = 0;
        return function() {
          return y += 45;
        };
      })();
      nodes = [
        {
          x: 50,
          y: y_axis(),
          r: 10,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 20,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 5,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 10,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 20,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 5,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 20,
          name: 'http://westlab.ac.keio.jp'
        }, {
          x: 50,
          y: y_axis(),
          r: 20,
          name: 'http://westlab.ac.keio.jp'
        }
      ];
      links = [];
      for (i = j = 0, ref = nodes.length - 2; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        links.push({
          source: nodes[i],
          target: nodes[i + 1]
        });
      }
      svg.selectAll(".line").data(links).enter().append("line").attr("x1", function(d) {
        return d.source.x;
      }).attr("y1", function(d) {
        return d.source.y;
      }).attr("x2", function(d) {
        return d.target.x;
      }).attr("y2", function(d) {
        return d.target.y;
      }).style("stroke", "#393b79");
      node = svg.selectAll(".nodes").data(nodes).enter().append("g");
      node.append("circle").attr("cx", function(d) {
        return d.x;
      }).attr("cy", function(d) {
        return d.y;
      }).attr("r", function(d) {
        return d.r;
      }).attr("fill", "#448AFF").attr("class", 'node');
      return node.append("text").attr("dx", 20).attr("dy", ".35em").text(function(d) {
        return d.name;
      }).attr("transform", function(d) {
        return "translate(" + (d.x + 100) + "," + d.y + ")";
      });
    };
    return {
      link: link,
      restrict: 'E'
    };
  });

}).call(this);

//# sourceMappingURL=browsing-graph.js.map
